[mapper]
"MODIFIED_SEQUENCE" = "Sequence"
"RAW_FILE_NAME" = "Raw file"
"PRECURSOR_CHARGE" = "Charge"
"QUANTIFICATION" = "Intensity"
"FASTA_HEADERS" = "Proteins"

[condition_mapper]
"240pg_10pg_H_Y_r1" = "A"
"240pg_10pg_H_Y_r2" = "A"
"240pg_10pg_H_Y_r3" = "A"
"200pg_50pg_H_Y_r1" = "B"
"200pg_50pg_H_Y_r2" = "B"
"200pg_50pg_H_Y_r3" = "B"

[run_mapper]
"240pg_10pg_H_Y_r1" = "240pg_10pg_H_Y_r1"
"240pg_10pg_H_Y_r2" = "240pg_10pg_H_Y_r2"
"240pg_10pg_H_Y_r3" = "240pg_10pg_H_Y_r3"
"200pg_50pg_H_Y_r1" = "200pg_50pg_H_Y_r1"
"200pg_50pg_H_Y_r2" = "200pg_50pg_H_Y_r2"
"200pg_50pg_H_Y_r3" = "200pg_50pg_H_Y_r3"

[species_mapper]
"_YEAST" = "YEAST"
"_HUMAN" = "HUMAN"

[modifications_parser]
"parse_column" = "Sequence"
"before_aa" = false
"isalpha" = true
"isupper" = true
"pattern" = "\\[(.*?)\\]"
"modification_dict" = {"[unimod:4]" = "Carbamidomethyl", "[unimod:1]" = "Acetyl", "[unimod:35]" = "Oxidation"}

[general]
"contaminant_flag" = "Cont_"
"decoy_flag" = false