[mapper]
"Sequence" = "Sequence"
"Raw file" = "Raw file"
"Proteins" = "Proteins"
"Modified sequence" = "Modified sequence"
"Charge" = "Charge"

[condition_mapper]
"240pg_10pg_H_Y_r1" = "A"
"240pg_10pg_H_Y_r2" = "A"
"240pg_10pg_H_Y_r3" = "A"
"200pg_50pg_H_Y_r1" = "B"
"200pg_50pg_H_Y_r2" = "B"
"200pg_50pg_H_Y_r3" = "B"

[run_mapper]
"240pg_10pg_H_Y_r1" = "240pg_10pg_H_Y_r1"
"240pg_10pg_H_Y_r2" = "240pg_10pg_H_Y_r2"
"240pg_10pg_H_Y_r3" = "240pg_10pg_H_Y_r3"
"200pg_50pg_H_Y_r1" = "200pg_50pg_H_Y_r1"
"200pg_50pg_H_Y_r2" = "200pg_50pg_H_Y_r2"
"200pg_50pg_H_Y_r3" = "200pg_50pg_H_Y_r3"

[species_mapper]
"_YEAST" = "YEAST"
"_HUMAN" = "HUMAN"

[modifications_parser]
"parse_column" = "Modified sequence"
"before_aa" = false
"isalpha" = true
"isupper" = true
"pattern" = "\\([^()]*\\)|\\([^()]*\\([^()]*\\)[^()]*\\)"
"modification_dict" = {"(ox)" = "Oxidation", "(ac)" = "Acetyl", "(oxidation (m))" = "Oxidation", "(acetyl (protein n-term))" = "Acetylation"}

[general]
"contaminant_flag" = "Cont_"
"decoy_flag" = true
